### ISSUE TITLE
Please implement OAuth login so that this tool works for more than an hour :)

### ISSUE THREAD

**Issue by atuttle** [rasky/trello-hipchat#1]
Trello example tokens only last for an hour.

![](https://www.evernote.com/shard/s240/sh/00276599-64ec-4ba8-89ac-e8152ac4dcd3/65af622f63a28f2316454e2edb295e33/deep/0/Screenshot%207/27/13%203:23%20PM.png)

**Comment by rasky** [comment]
I've updated the documentation, providing a link that allows you to generate non-expiring tokens.
